sync_to_monitor no
input_delay 0
repaint_delay 2
# Вимкнення анімації курсору (теж може гальмувати)
cursor_blink_interval 0
include ~/.cache/wal/colors-kitty.conf
background_opacity 0.8
hide_window_decorations yes
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0
allow_remote_control yes
listen_on unix:/tmp/mykitty
